field: 0cf0f2ac-21f3-4633-a67e-85c7d6cee899 # Practical Block
fieldLayouts:
  26b9ebdb-dceb-4f7b-9ca1-7aad61727a1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4e0f1a97-cc16-4c9b-b322-9892d6ba6ea4 # image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f40b9a-3cb1-4edb-bfad-5bc06326156a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea8fcad2-6039-49a4-bd4c-bb63f198da5c # Img Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f127d5f5-bab3-45ef-b93a-9384f1055c9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e2adf2c-03e7-41ce-b313-d2235b4099e8 # Info Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cb0675e-9253-42b5-a41b-720982838030
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 401697fa-4956-4557-89d5-2bacae44e5ba # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecf7faab-0ac6-4669-a100-86664c771932
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d52ad1d-e1a5-48de-bdd3-dbe89f9adaac # Display Switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2079c9c2-e31b-49b1-908a-15dd584201de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60c2101b-3b70-4350-8556-22b8d2129a00
        userCondition: null
fields:
  3d52ad1d-e1a5-48de-bdd3-dbe89f9adaac: # Display Switch
    columnSuffix: capcmawg
    contentColumnType: boolean
    fieldGroup: null
    handle: displaySwitch
    instructions: 'Choose how you want to display the content. By default, the image is on the left side, but you can switch it to the right side by turning on the switch. '
    name: 'Display Switch'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: reverse
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  4e0f1a97-cc16-4c9b-b322-9892d6ba6ea4: # image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Add an image'
    name: image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:9daad15a-bb36-4771-9f6c-3b1dd16f1543' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9daad15a-bb36-4771-9f6c-3b1dd16f1543' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6e2adf2c-03e7-41ce-b313-d2235b4099e8: # Info Title
    columnSuffix: mjllxffm
    contentColumnType: string(200)
    fieldGroup: null
    handle: infoTitle
    instructions: 'Write title here'
    name: 'Info Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 50
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  401697fa-4956-4557-89d5-2bacae44e5ba: # Paragraph
    columnSuffix: fwxcussl
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: 'Write information here'
    name: Paragraph
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ea8fcad2-6039-49a4-bd4c-bb63f198da5c: # Img Description
    columnSuffix: txzzsfth
    contentColumnType: string(80)
    fieldGroup: null
    handle: imgDescription
    instructions: 'Write a description for the image. This will not be visible on the page. '
    name: 'Img Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 20
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: Image
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: informationBlock
name: 'Information Block'
sortOrder: 1
