fieldLayouts:
  9371714b-45da-4d95-b0b8-eeb782228a96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1432010c-0c26-494c-a973-c082e908b370
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55df64a0-704c-4464-b38e-fdf99dcd207c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf7038c3-4054-48b9-90b0-670e4a49a4b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73b77ca5-3c73-4fed-85c7-ea95ddb7f1a4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f573121c-8b4c-47df-820c-0999a4e967b3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15631b12-950c-4fcf-8fed-06aba320f122
        userCondition: null
handle: tags
name: tags
