fieldLayouts:
  368f7115-5433-4f6f-96b3-42c1fa57edb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0713f3c8-2611-4c46-b94c-aa2add5b0718
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b897e2b1-d4d5-4fb8-b4e6-debd0a228348 # Artist Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b1d9494-9ed4-4d02-98e4-5f3c737b1a6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be98dd5a-0e66-4f97-9875-80d6f25b11f9 # Artist Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5071c6a-29fd-4c75-bb70-7db2eaac40b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7fb27517-c8be-46e4-b189-53fee60e4bfd # Artist Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ace66e3-774c-43a5-bc19-2796b572b1f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2cfaf68a-146b-4d40-b7d9-c1f70a40cd11 # Stage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae7c9abe-4b98-453a-a13b-3ada19d06a02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04614edc-2e8d-4213-abba-4792b0d46820 # Artist Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60053082-6c22-4702-9496-9552573db593
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd101e26-e6d2-4d4a-99f9-a2b62e02edd6 # location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ab05e25-2f1c-4f40-9c80-3688f466d7f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 19bc3333-d1ef-45ec-8dd6-0c4510802dd9 # Songs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bafe1e1a-65c5-4605-a8c0-a31a2c5991ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f047063f-e2e5-4dcc-aea7-6f6203d5cc6b # paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 776156e4-bc04-44c5-a45f-147525970499
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55d0c769-a861-4069-95e5-43174e9b3d6d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55df64a0-704c-4464-b38e-fdf99dcd207c # Day One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a327e34-d92f-43ef-8236-13f579f322c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73b77ca5-3c73-4fed-85c7-ea95ddb7f1a4 # Day Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dd6e1e5-0847-4939-9dfa-6bd251b11390
            userCondition: null
            warning: null
            width: 100
        name: Tags
        uid: 4c6fe0e2-5d82-43c3-8546-e57dcb55e245
        userCondition: null
handle: artists
hasTitleField: true
name: Artists
section: 3d0f68aa-8059-4a85-8cd9-833c4f0e39dd # Artists
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
