fieldLayouts:
  f64665e9-d9c8-41a5-bd07-5d247ec58b37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9d6c7c4-cde7-4c7a-84f1-ae692d8d9eab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78fb5cea-0619-486b-bdc6-368195500948 # year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b05402d-c504-4273-93ba-ea1f78374190
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66a78b13-da8f-4adc-b463-278040fca9e8 # Intro Name Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd5fd68e-722a-4664-9027-6a3ebbfda7ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd101e26-e6d2-4d4a-99f9-a2b62e02edd6 # location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee8f037e-20ba-48ad-96c9-3e69f2bfbc19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ba36a44-66d8-48cf-abb7-4dbac9a804ae # Festival Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac27864c-99ae-47af-afe3-1c1ea3ab95bb
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 00f1d1e7-2330-4384-9012-1bda49c90e87
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 3ab0172f-fb89-41e3-a431-f39a192e79cc # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
