fieldLayouts:
  f64665e9-d9c8-41a5-bd07-5d247ec58b37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9d6c7c4-cde7-4c7a-84f1-ae692d8d9eab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f047063f-e2e5-4dcc-aea7-6f6203d5cc6b # paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea6646b6-34dd-4e58-af9f-efac6470bed6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00f1d1e7-2330-4384-9012-1bda49c90e87
        userCondition: null
handle: home
hasTitleField: false
name: home
section: 3ab0172f-fb89-41e3-a431-f39a192e79cc # home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
