fieldLayouts:
  d87910b6-3154-44d8-8826-0a00376971f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a7dd21c-4e8f-4308-84c5-9ab261ee5fea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cf0f2ac-21f3-4633-a67e-85c7d6cee899 # Practical Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: feba1b85-b0f1-494c-b18a-402b2c3858f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3edb9326-b0e4-4e3e-b87b-13a87bfa7c77 # Google Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45a5131c-1391-4cbe-944d-3f143f76be39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c58edb0-d8d6-445b-9ce9-2fc1e0cad2a6
        userCondition: null
handle: practical
hasTitleField: false
name: Practical
section: c234393c-c53b-4616-88af-6231e1937139 # Practical
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
