fieldLayouts:
  108737d2-acca-46fd-b99e-741ecafa68a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae103e05-11ad-47b4-a590-50c1291efd68
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47d8c7ae-3f77-4bf6-83c9-22bc64c9e560
        userCondition: null
handle: ticketsPage
hasTitleField: false
name: 'Tickets Page'
section: 932691c9-9e52-42af-8bb8-c219d5ec45b5 # Tickets Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
