fieldLayouts:
  be3ecbb6-3396-43cc-a5ed-5644615ac92f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2dbd93fa-45bb-44a4-80f7-9b82fdccd651
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50a8d1e0-be10-4059-9e34-595db50a9cf0
        userCondition: null
fs: images
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
