columnSuffix: wcmxnftd
contentColumnType: string(100)
fieldGroup: 0637d01f-a0c9-4fbd-beff-53a3031fd152 # artists
handle: artistTime
instructions: 'Write the scheduled time for the artist to perform'
name: 'Artist Time'
searchable: false
settings:
  byteLimit: null
  charLimit: 25
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '12:00PM - 1:00PM'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
