columnSuffix: clysnqnn
contentColumnType: datetime
fieldGroup: c908d6c4-9450-47ff-9859-5dadeacca604 # schedule
handle: performanceTime
instructions: 'Determine the date and time the performance takes place'
name: 'Performance Time'
searchable: false
settings:
  max: '2023-09-17T00:00:00-07:00'
  min: '2023-09-16T00:00:00-07:00'
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
