columnSuffix: vfuqcfdo
contentColumnType: text
fieldGroup: 0637d01f-a0c9-4fbd-beff-53a3031fd152 # artists
handle: songs
instructions: 'Which songs does the band/artist play? List them down in one line, but add comma in between.'
name: Songs
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Þrahyggja, Malbik, Sjukir i mig'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
