columnSuffix: null
contentColumnType: string
fieldGroup: c908d6c4-9450-47ff-9859-5dadeacca604 # schedule
handle: stageCategory
instructions: 'Stage name '
name: 'Stage Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a stage name '
  showSiteMenu: true
  source: 'group:884355f6-0b7e-408f-836b-6c73dda355df' # Stage Category
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
