columnSuffix: xtcffhyz
contentColumnType: string(100)
fieldGroup: 0637d01f-a0c9-4fbd-beff-53a3031fd152 # artists
handle: stage
instructions: 'Write the stage name here'
name: Stage
searchable: false
settings:
  byteLimit: null
  charLimit: 25
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Main stage'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
