columnSuffix: nslbbwxa
contentColumnType: text
fieldGroup: 1dcba13b-bf8d-414e-839a-eb1dfd1c13d6 # Common
handle: year
instructions: 'What year does it take place?'
name: year
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
