dateModified: 1689472735
email:
  fromEmail: kristin.erlingsdottir@student.howest.be
  fromName: web3-retake
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/img'
    type: craft\fs\Local
    url: '@web/assets/img'
meta:
  __names__:
    1a8d3fa9-82a7-4684-bc8c-8054e8665b8f: Practical # Practical
    1dcba13b-bf8d-414e-839a-eb1dfd1c13d6: Common # Common
    2cfaf68a-146b-4d40-b7d9-c1f70a40cd11: Stage # Stage
    3ab0172f-fb89-41e3-a431-f39a192e79cc: Home # Home
    3d0f68aa-8059-4a85-8cd9-833c4f0e39dd: Artists # Artists
    3eb43c32-91df-4ed7-9d2a-45230c704919: Artists # Artists
    7ba36a44-66d8-48cf-abb7-4dbac9a804ae: 'Festival Date' # Festival Date
    7fb27517-c8be-46e4-b189-53fee60e4bfd: 'Artist Date' # Artist Date
    9daad15a-bb36-4771-9f6c-3b1dd16f1543: Uploads # Uploads
    17b2f273-58ce-4b03-854e-4f98b6e7a54d: web3-retake # web3-retake
    19b07e91-6fff-4f1b-99d8-c068407945a4: 'Artist Name' # Artist Name
    19bc3333-d1ef-45ec-8dd6-0c4510802dd9: Songs # Songs
    50b36d0b-47fa-4167-bd65-d24edc1d65f0: Schedule # Schedule
    66a78b13-da8f-4adc-b463-278040fca9e8: 'Intro Name Block' # Intro Name Block
    72dd30ae-32fb-4a41-a4de-ffd82a4c00fc: home # home
    78fb5cea-0619-486b-bdc6-368195500948: year # year
    0637d01f-a0c9-4fbd-beff-53a3031fd152: artists # artists
    1284d164-214c-497a-a9ad-f9082785eb40: Schedule # Schedule
    04614edc-2e8d-4213-abba-4792b0d46820: 'Artist Name' # Artist Name
    8732b219-fd37-4636-8400-8ebb50f1b42a: 'Date Year' # Date Year
    74433564-87e3-4279-bddf-f2e72f868d5b: web3-retake # web3-retake
    b897e2b1-d4d5-4fb8-b4e6-debd0a228348: 'Artist Image' # Artist Image
    be98dd5a-0e66-4f97-9875-80d6f25b11f9: 'Artist Time' # Artist Time
    c908d6c4-9450-47ff-9859-5dadeacca604: schedule # schedule
    c85091e3-cc71-44d1-92dc-112b08b449d8: practical # practical
    c234393c-c53b-4616-88af-6231e1937139: Practical # Practical
    cd101e26-e6d2-4d4a-99f9-a2b62e02edd6: location # location
    e8803525-0da4-488a-9e15-fa60ab0cb39b: 'Intro Name' # Intro Name
    f047063f-e2e5-4dcc-aea7-6f6203d5cc6b: paragraph # paragraph
    fe37ed78-e85e-4fdb-8ac9-ed64637a7765: Home # Home
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: web3-retake
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
