defaultPlacement: end
enableVersioning: true
handle: artists
name: Artists
propagationMethod: all
siteSettings:
  17b2f273-58ce-4b03-854e-4f98b6e7a54d: # web3-retake
    enabledByDefault: true
    hasUrls: true
    template: _/artists/_entry
    uriFormat: 'artists/{slug}'
type: channel
